feat: создать каркас SpringBoot прил. Filmorate
Eleonora-Y/java-filmorate pull request #1
Opened 2023-02-01 15:32 UTC by Eleonora-Y

2023-02-01 16:18 UTC, Eleonora-Y commented
Ура

2023-02-01 18:32 UTC, db-exp requested changes

2023-02-01 18:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!films.containsKey(film.getId())) {
вот тут тоже нужно проверять все ограничения по фильму как и при создании

2023-02-01 18:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName().isEmpty()) {
давай объединим с предыдущим if-ом?

2023-02-01 18:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            users.put(user.getId(), user);
тут тоже нужно проверять ограничения по данным пользователя

2023-02-01 18:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void logWarnAndThrowException(String message) {
лучше вынести в отдельный класс-утилиту и сделать статическим методом

2023-02-01 21:14 UTC, Eleonora-Y commented
Дмитрий, я все поправила, кроме объединения if .. ( if (user.getName().isEmpty() || user.getName() == null) ) не работает, давайте оставим так, пожалуйста)

2023-02-01 22:42 UTC, db-exp requested changes

2023-02-01 22:42 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
Проверки на валидацию дублируются в методах - давай вынесем в отдельный метод?

2023-02-01 22:42 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Код валидации нужно вынести в отдельный метод, чтобы не дублировать

2023-02-01 22:42 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName().isEmpty()) {
Тут можно так if (user.getName() == null || user.getName().isEmpty()) тогда если null не упадет на второй проверке

2023-02-02 12:13 UTC, db-exp approved these changes

2023-02-02 20:33 UTC, merged